version: '3.8'
x-database-variables:
  &database-variables
  SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mentoria_academica
  SPRING_DATASOURCE_USERNAME: user
  SPRING_DATASOURCE_PASSWORD: password

services:
  db:
    image: postgres
    container_name: db_postgresql_mentoria_academica
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: mentoria_academica
    ports:
      - "5432:5432"