spring:
    application:
      name: mentoria-academica
    datasource:
        url:  ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
    threads:
      virtual:
        enabled: true
server:
  tomcat:
    threads:
      max: 200