spring:
    application:
      name: mentoria-academica
    datasource:
        url:  ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
    threads:
      virtual:
        enabled: true
    mail:
      host: smtp.gmail.com
      port: 587
      username: ${EMAIL_USERNAME}
      password: ${EMAIL_PASSWORD}
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
url:
  document: ${URL_SPRINGDOC}
  